version: 2.1

orbs:
  orb-tools: circleci/orb-tools@7.3.0

workflows:
  pack-and-publish:
    jobs:
      - orb-tools/pack
      - orb-tools/publish-dev:
          context: org-global
          orb-name: picturepipe/sentry-cli
          requires:
            - orb-tools/pack
