version: 2.1

orbs:
  orb-tools: circleci/orb-tools@7.3.0

workflows:
  validate-and-publish:
    jobs:
      - orb-tools/publish-dev:
          context: org-global
          orb-name: picturepipe/sentry-cli
          orb-path: src/orb.yml
          validate: true
