version: 2.1

orbs:
  orb-tools: circleci/orb-tools@7.3.0

workflows:
  validate-and-publish:
    jobs:
      - orb-tools/publish:
          context: org-global
          orb-path: src/orb.yml
          orb-ref: picturepipe/sentry-cli@dev:{$CIRCLE_BRANCH}
